name: package
on:
  push:
    branches: [ main, '**/copilot/**', 'copilot/**' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Build dual outputs
        run: node build.js
      - name: List outputs (debug)
        run: |
          echo "::group::dist_server"; ls -la dist_server || true; echo "::endgroup::"
          echo "::group::dist_local";  ls -la dist_local  || true;  echo "::endgroup::"
      - name: Verify assets (server)
        if: ${{ hashFiles('dist_server/index.html') != '' }}
        run: cd dist_server && node ../verify-assets.js
      - name: Verify assets (local)
        if: ${{ hashFiles('dist_local/index.html') != '' }}
        run: cd dist_local && node ../verify-assets.js
      - name: Zip SERVER
        if: ${{ hashFiles('dist_server/**') != '' }}
        run: cd dist_server && zip -r ../SERVER.zip .
      - name: Zip LOCAL
        if: ${{ hashFiles('dist_local/**') != '' }}
        run: cd dist_local && zip -r ../LOCAL.zip .
      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('SERVER.zip') != '' }}
        with: { name: SERVER.zip, path: SERVER.zip, retention-days: 30 }
      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('LOCAL.zip') != '' }}
        with: { name: LOCAL.zip, path: LOCAL.zip, retention-days: 30 }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
name: package
on:
  push:
    branches: [ main, '**/copilot/**', 'copilot/**' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Build dual outputs
        run: node build.js
      - name: List outputs (debug)
        run: |
          echo "::group::dist_server"; ls -la dist_server || true; echo "::endgroup::"
          echo "::group::dist_local";  ls -la dist_local  || true;  echo "::endgroup::"
      - name: Verify assets (server)
        if: ${{ hashFiles('dist_server/index.html') != '' }}
        run: cd dist_server && node ../verify-assets.js
      - name: Verify assets (local)
        if: ${{ hashFiles('dist_local/index.html') != '' }}
        run: cd dist_local && node ../verify-assets.js
      - name: Zip SERVER
        if: ${{ hashFiles('dist_server/**') != '' }}
        run: cd dist_server && zip -r ../SERVER.zip .
      - name: Zip LOCAL
        if: ${{ hashFiles('dist_local/**') != '' }}
        run: cd dist_local && zip -r ../LOCAL.zip .
      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('SERVER.zip') != '' }}
        with: { name: SERVER.zip, path: SERVER.zip, retention-days: 30 }
      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('LOCAL.zip') != '' }}
        with: { name: LOCAL.zip, path: LOCAL.zip, retention-days: 30 }
  <a class="logo-wrap" href="/">AA</a><nav class="primary"><a href="/">Home</a></nav>
</div></header>
<section class="section"><h2>Bootstrap Home</h2>
<div class="starfield"></div>
<div class="grid">
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
</div>
</section>
<script src="assets/app.js?v=bootstrap"></script>
</body></html>
HTML
          fi
          if [ ! -f index_diag.html ]; then
            cat > index_diag.html <<'HTML'
<!doctype html><html><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="assets/style.css?v=bootstrap">
<style>.diag{padding:12px;background:#111;color:#fff}</style>
</head><body>
<div class="diag">Diag: CSS/JS present.</div>
<script src="assets/app.js?v=bootstrap"></script>
</body></html>
HTML
          fi

      - name: Build dual outputs
        run: node build.js

      - name: List outputs (debug)
        run: |
          echo "::group::tree dist_server"; ls -la dist_server || true; echo "::endgroup::"
          echo "::group::tree dist_local";  ls -la dist_local  || true; echo "::endgroup::"

      - name: Verify assets (server)
        if: ${{ hashFiles('dist_server/index.html') != '' }}
        run: cd dist_server && node ../verify-assets.js

      - name: Verify assets (local)
        if: ${{ hashFiles('dist_local/index.html') != '' }}
        run: cd dist_local && node ../verify-assets.js

      - name: Zip SERVER
        if: ${{ hashFiles('dist_server/**') != '' }}
        run: cd dist_server && zip -r ../SERVER.zip .

      - name: Zip LOCAL
        if: ${{ hashFiles('dist_local/**') != '' }}
        run: cd dist_local && zip -r ../LOCAL.zip .

      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('SERVER.zip') != '' }}
        with:
          name: SERVER.zip
          path: SERVER.zip
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('LOCAL.zip') != '' }}
        with:
          name: LOCAL.zip
          path: LOCAL.zip
          retention-days: 30
=======
        with: { node-version: '20' }
      - name: Build dual outputs
        run: node build.js
      - name: List outputs (debug)
        run: |
          echo "::group::dist_server"; ls -la dist_server || true; echo "::endgroup::"
          echo "::group::dist_local";  ls -la dist_local  || true;  echo "::endgroup::"
      - name: Verify assets (server)
        if: ${{ hashFiles('dist_server/index.html') != '' }}
        run: cd dist_server && node ../verify-assets.js
      - name: Verify assets (local)
        if: ${{ hashFiles('dist_local/index.html') != '' }}
        run: cd dist_local && node ../verify-assets.js
      - name: Zip SERVER
        if: ${{ hashFiles('dist_server/**') != '' }}
        run: cd dist_server && zip -r ../SERVER.zip .
      - name: Zip LOCAL
        if: ${{ hashFiles('dist_local/**') != '' }}
        run: cd dist_local && zip -r ../LOCAL.zip .
      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('SERVER.zip') != '' }}
        with: { name: SERVER.zip, path: SERVER.zip, retention-days: 30 }
      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('LOCAL.zip') != '' }}
        with: { name: LOCAL.zip, path: LOCAL.zip, retention-days: 30 }
>>>>>>> 758da6f (ci: strict verifier + package workflow)
