name: package
on:
  push:
    branches: [ main, '**/copilot/**', 'copilot/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build dual outputs
        run: node build.js

      - name: List outputs (debug)
        run: |
          echo "::group::tree dist_server"
          ls -la dist_server || true
          echo "::endgroup::"
          echo "::group::tree dist_local"
          ls -la dist_local || true
          echo "::endgroup::"

      - name: Verify assets (server)
        if: ${{ hashFiles('dist_server/index.html') != '' }}
        run: cd dist_server && node ../verify-assets.js

      - name: Verify assets (local)
        if: ${{
