name: package
on:
  push:
    branches: [ main, '**/copilot/**', 'copilot/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Bootstrap minimal files if missing so CI can’t fail on basics
      - name: Bootstrap minimal site files (if missing)
        run: |
          set -e
          mkdir -p assets images/gallery
          if [ ! -f assets/style.css ]; then
            cat > assets/style.css <<'CSS'
:root{--z-header:100;--z-logo:90;--z-award:80}
html,body{margin:0;height:100%;background:#0b0b12;color:#fff;font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Calibri,Arial,sans-serif}
.starfield{position:absolute;inset:0;opacity:.65}
.starfield::before,.starfield::after{content:"";position:absolute;inset:0;background:radial-gradient(2px 2px at 12% 22%, #fff 60%, transparent 61%),radial-gradient(1px 1px at 31% 78%, #fff 60%, transparent 61%);animation:twinkle 3s ease-in-out infinite}
@keyframes twinkle{0%,100%{opacity:.45}50%{opacity:1}}
.flip,.panel{outline:4px solid #fff;box-shadow:inset 0 0 0 18px rgba(255,255,255,.25);background:#000;border-radius:8px}
.flip img,.panel img{width:100%;height:100%;object-fit:contain;background:#000}
CSS
          fi
          if [ ! -f assets/app.js ]; then
            cat > assets/app.js <<'JS'
document.addEventListener('DOMContentLoaded', () => {
  const award = document.querySelector('.award-vert');
  if (award) setTimeout(() => award.classList.add('show'), 5000);
});
JS
          fi
          if [ ! -f index.html ]; then
            cat > index.html <<'HTML'
<!doctype html><html><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="assets/style.css?v=bootstrap">
</head><body>
<header class="topbar"><div class="topbar-inner">
  <a class="logo-wrap" href="/">AA</a><nav class="primary"><a href="/">Home</a></nav>
</div></header>
<section class="section"><h2>Bootstrap Home</h2>
<div class="starfield"></div>
<div class="grid">
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
  <div class="panel"><img alt=""><div class="mask"><div class="overlayText"></div></div></div>
</div>
</section>
<script src="assets/app.js?v=bootstrap"></script>
</body></html>
HTML
          fi
          if [ ! -f index_diag.html ]; then
            cat > index_diag.html <<'HTML'
<!doctype html><html><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="assets/style.css?v=bootstrap">
<style>.diag{padding:12px;background:#111;color:#fff}</style>
</head><body>
<div class="diag">Diag: CSS/JS present.</div>
<script src="assets/app.js?v=bootstrap"></script>
</body></html>
HTML
          fi

      - name: Build dual outputs
        run: node build.js

      - name: List outputs (debug)
        run: |
          echo "::group::tree dist_server"; ls -la dist_server || true; echo "::endgroup::"
          echo "::group::tree dist_local";  ls -la dist_local  || true; echo "::endgroup::"

      - name: Verify assets (server)
        if: ${{ hashFiles('dist_server/index.html') != '' }}
        run: cd dist_server && node ../verify-assets.js

      - name: Verify assets (local)
        if: ${{ hashFiles('dist_local/index.html') != '' }}
        run: cd dist_local && node ../verify-assets.js

      - name: Zip SERVER
        if: ${{ hashFiles('dist_server/**') != '' }}
        run: cd dist_server && zip -r ../SERVER.zip .

      - name: Zip LOCAL
        if: ${{ hashFiles('dist_local/**') != '' }}
        run: cd dist_local && zip -r ../LOCAL.zip .

      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('SERVER.zip') != '' }}
        with:
          name: SERVER.zip
          path: SERVER.zip
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ hashFiles('LOCAL.zip') != '' }}
        with:
          name: LOCAL.zip
          path: LOCAL.zip
          retention-days: 30
